package com.tutoraca.firstProject.controller;

import com.tutoraca.firstProject.model.Book;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/book")
public class BookController {

    @GetMapping("/demo")
    public Book showBookDemo() {
        // No-args constructor and setters below are generated by Lombok.
        Book book = new Book();
        book.setId(1);
        book.setTitle("Spring Boot");
        book.setAuthor("Himanshu");
        book.setPrice(499.0);
        return book;
    }

    @GetMapping("/demo2")
    public String showBookDemo2() {
        // All-args constructor and toString() below are generated by Lombok.
        Book book = new Book(2, "Spring AOP", "Tutor", 599.0);
        return book.toString();
    }
}
